#############################################################################
# Makefile for building: /opt/raspberrytomb/raspberrytomb
# Generated by qmake (2.01a) (Qt 4.7.2) on: Sun Mar 25 00:25:35 2012
# Project:  raspberrytomb.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile raspberrytomb.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I/usr/X11R6/include -I/opt/raspberrytomb/.moc -I/opt/raspberrytomb/.ui
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -lQtSql -lQtOpenGL -lQtGui -lQtNetwork -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = /opt/raspberrytomb/.obj/

####### Files

SOURCES       = src/main.cpp \
		src/beaglemain.cpp \
		src/sync.cpp \
		src/songObj.cpp \
		src/readDB.cpp \
		src/qmpwidget.cpp \
		src/preferences.cpp \
		src/prefdialog.cpp \
		src/mysqlconn.cpp \
		src/mplaycon.cpp \
		src/about.cpp \
		src/newplaylist.cpp \
		src/playlistobj.cpp \
		src/openplaylist.cpp \
		src/radioObj.cpp /opt/raspberrytomb/.moc/moc_beaglemain.cpp \
		/opt/raspberrytomb/.moc/moc_qmpyuvreader.cpp \
		/opt/raspberrytomb/.moc/moc_qmpwidget.cpp \
		/opt/raspberrytomb/.moc/moc_prefdialog.cpp \
		/opt/raspberrytomb/.moc/moc_about.cpp \
		/opt/raspberrytomb/.moc/moc_newplaylist.cpp \
		/opt/raspberrytomb/.moc/moc_openplaylist.cpp \
		/opt/raspberrytomb/.rcc/qrc_BTres.cpp
OBJECTS       = /opt/raspberrytomb/.obj/main.o \
		/opt/raspberrytomb/.obj/beaglemain.o \
		/opt/raspberrytomb/.obj/sync.o \
		/opt/raspberrytomb/.obj/songObj.o \
		/opt/raspberrytomb/.obj/readDB.o \
		/opt/raspberrytomb/.obj/qmpwidget.o \
		/opt/raspberrytomb/.obj/preferences.o \
		/opt/raspberrytomb/.obj/prefdialog.o \
		/opt/raspberrytomb/.obj/mysqlconn.o \
		/opt/raspberrytomb/.obj/mplaycon.o \
		/opt/raspberrytomb/.obj/about.o \
		/opt/raspberrytomb/.obj/newplaylist.o \
		/opt/raspberrytomb/.obj/playlistobj.o \
		/opt/raspberrytomb/.obj/openplaylist.o \
		/opt/raspberrytomb/.obj/radioObj.o \
		/opt/raspberrytomb/.obj/moc_beaglemain.o \
		/opt/raspberrytomb/.obj/moc_qmpyuvreader.o \
		/opt/raspberrytomb/.obj/moc_qmpwidget.o \
		/opt/raspberrytomb/.obj/moc_prefdialog.o \
		/opt/raspberrytomb/.obj/moc_about.o \
		/opt/raspberrytomb/.obj/moc_newplaylist.o \
		/opt/raspberrytomb/.obj/moc_openplaylist.o \
		/opt/raspberrytomb/.obj/qrc_BTres.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		raspberrytomb.pro
QMAKE_TARGET  = raspberrytomb
DESTDIR       = /opt/raspberrytomb/
TARGET        = /opt/raspberrytomb/raspberrytomb

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): /opt/raspberrytomb/.ui/ui_prefdialog.h /opt/raspberrytomb/.ui/ui_about.h /opt/raspberrytomb/.ui/ui_newplaylist.h /opt/raspberrytomb/.ui/ui_beaglemain.h /opt/raspberrytomb/.ui/ui_openplaylist.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) /opt/raspberrytomb/ || $(MKDIR) /opt/raspberrytomb/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: raspberrytomb.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile raspberrytomb.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtSql.prl:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile raspberrytomb.pro

dist: 
	@$(CHK_DIR_EXISTS) /opt/raspberrytomb/.obj/raspberrytomb1.0.0 || $(MKDIR) /opt/raspberrytomb/.obj/raspberrytomb1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) /opt/raspberrytomb/.obj/raspberrytomb1.0.0/ && $(COPY_FILE) --parents src/beaglemain.h src/sync.h src/songObj.h src/readDB.h src/qmpyuvreader.h src/qmpwidget.h src/preferences.h src/prefdialog.h src/mysqlconn.h src/mplaycon.h src/about.h src/newplaylist.h src/playlistobj.h src/sync.h src/songObj.h src/readDB.h src/qmpyuvreader.h src/qmpwidget.h src/preferences.h src/prefdialog.h src/playlistobj.h src/newplaylist.h src/mysqlconn.h src/mplaycon.h src/beaglemain.h src/about.h src/openplaylist.h src/radioObj.h /opt/raspberrytomb/.obj/raspberrytomb1.0.0/ && $(COPY_FILE) --parents images/BTres.qrc /opt/raspberrytomb/.obj/raspberrytomb1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/beaglemain.cpp src/sync.cpp src/songObj.cpp src/readDB.cpp src/qmpwidget.cpp src/preferences.cpp src/prefdialog.cpp src/mysqlconn.cpp src/mplaycon.cpp src/about.cpp src/newplaylist.cpp src/playlistobj.cpp src/openplaylist.cpp src/radioObj.cpp /opt/raspberrytomb/.obj/raspberrytomb1.0.0/ && $(COPY_FILE) --parents src/prefdialog.ui src/about.ui src/newplaylist.ui src/beaglemain.ui src/openplaylist.ui /opt/raspberrytomb/.obj/raspberrytomb1.0.0/ && (cd `dirname /opt/raspberrytomb/.obj/raspberrytomb1.0.0` && $(TAR) raspberrytomb1.0.0.tar raspberrytomb1.0.0 && $(COMPRESS) raspberrytomb1.0.0.tar) && $(MOVE) `dirname /opt/raspberrytomb/.obj/raspberrytomb1.0.0`/raspberrytomb1.0.0.tar.gz . && $(DEL_FILE) -r /opt/raspberrytomb/.obj/raspberrytomb1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: /opt/raspberrytomb/.moc/moc_beaglemain.cpp /opt/raspberrytomb/.moc/moc_qmpyuvreader.cpp /opt/raspberrytomb/.moc/moc_qmpwidget.cpp /opt/raspberrytomb/.moc/moc_prefdialog.cpp /opt/raspberrytomb/.moc/moc_about.cpp /opt/raspberrytomb/.moc/moc_newplaylist.cpp /opt/raspberrytomb/.moc/moc_qmpyuvreader.cpp /opt/raspberrytomb/.moc/moc_qmpwidget.cpp /opt/raspberrytomb/.moc/moc_prefdialog.cpp /opt/raspberrytomb/.moc/moc_newplaylist.cpp /opt/raspberrytomb/.moc/moc_beaglemain.cpp /opt/raspberrytomb/.moc/moc_about.cpp /opt/raspberrytomb/.moc/moc_openplaylist.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) /opt/raspberrytomb/.moc/moc_beaglemain.cpp /opt/raspberrytomb/.moc/moc_qmpyuvreader.cpp /opt/raspberrytomb/.moc/moc_qmpwidget.cpp /opt/raspberrytomb/.moc/moc_prefdialog.cpp /opt/raspberrytomb/.moc/moc_about.cpp /opt/raspberrytomb/.moc/moc_newplaylist.cpp /opt/raspberrytomb/.moc/moc_qmpyuvreader.cpp /opt/raspberrytomb/.moc/moc_qmpwidget.cpp /opt/raspberrytomb/.moc/moc_prefdialog.cpp /opt/raspberrytomb/.moc/moc_newplaylist.cpp /opt/raspberrytomb/.moc/moc_beaglemain.cpp /opt/raspberrytomb/.moc/moc_about.cpp /opt/raspberrytomb/.moc/moc_openplaylist.cpp
/opt/raspberrytomb/.moc/moc_beaglemain.cpp: src/sync.h \
		src/mysqlconn.h \
		src/songObj.h \
		src/readDB.h \
		src/radioObj.h \
		src/preferences.h \
		src/mplaycon.h \
		src/qmpwidget.h \
		src/playlistobj.h \
		src/prefdialog.h \
		src/about.h \
		src/newplaylist.h \
		src/openplaylist.h \
		src/beaglemain.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/beaglemain.h -o /opt/raspberrytomb/.moc/moc_beaglemain.cpp

/opt/raspberrytomb/.moc/moc_qmpyuvreader.cpp: src/qmpyuvreader.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qmpyuvreader.h -o /opt/raspberrytomb/.moc/moc_qmpyuvreader.cpp

/opt/raspberrytomb/.moc/moc_qmpwidget.cpp: src/qmpwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qmpwidget.h -o /opt/raspberrytomb/.moc/moc_qmpwidget.cpp

/opt/raspberrytomb/.moc/moc_prefdialog.cpp: src/preferences.h \
		src/prefdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/prefdialog.h -o /opt/raspberrytomb/.moc/moc_prefdialog.cpp

/opt/raspberrytomb/.moc/moc_about.cpp: src/about.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/about.h -o /opt/raspberrytomb/.moc/moc_about.cpp

/opt/raspberrytomb/.moc/moc_newplaylist.cpp: src/preferences.h \
		src/newplaylist.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/newplaylist.h -o /opt/raspberrytomb/.moc/moc_newplaylist.cpp

/opt/raspberrytomb/.moc/moc_qmpyuvreader.cpp: src/qmpyuvreader.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qmpyuvreader.h -o /opt/raspberrytomb/.moc/moc_qmpyuvreader.cpp

/opt/raspberrytomb/.moc/moc_qmpwidget.cpp: src/qmpwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qmpwidget.h -o /opt/raspberrytomb/.moc/moc_qmpwidget.cpp

/opt/raspberrytomb/.moc/moc_prefdialog.cpp: src/preferences.h \
		src/prefdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/prefdialog.h -o /opt/raspberrytomb/.moc/moc_prefdialog.cpp

/opt/raspberrytomb/.moc/moc_newplaylist.cpp: src/preferences.h \
		src/newplaylist.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/newplaylist.h -o /opt/raspberrytomb/.moc/moc_newplaylist.cpp

/opt/raspberrytomb/.moc/moc_beaglemain.cpp: src/sync.h \
		src/mysqlconn.h \
		src/songObj.h \
		src/readDB.h \
		src/radioObj.h \
		src/preferences.h \
		src/mplaycon.h \
		src/qmpwidget.h \
		src/playlistobj.h \
		src/prefdialog.h \
		src/about.h \
		src/newplaylist.h \
		src/openplaylist.h \
		src/beaglemain.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/beaglemain.h -o /opt/raspberrytomb/.moc/moc_beaglemain.cpp

/opt/raspberrytomb/.moc/moc_about.cpp: src/about.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/about.h -o /opt/raspberrytomb/.moc/moc_about.cpp

/opt/raspberrytomb/.moc/moc_openplaylist.cpp: src/preferences.h \
		src/openplaylist.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/openplaylist.h -o /opt/raspberrytomb/.moc/moc_openplaylist.cpp

compiler_rcc_make_all: /opt/raspberrytomb/.rcc/qrc_BTres.cpp
compiler_rcc_clean:
	-$(DEL_FILE) /opt/raspberrytomb/.rcc/qrc_BTres.cpp
/opt/raspberrytomb/.rcc/qrc_BTres.cpp: images/BTres.qrc \
		images/RWD_icon.png \
		images/PAUSE_icon.png \
		images/RRWD_icon.png \
		images/FFWD_icon.png \
		images/beagletomb_icon.png \
		images/STOP_icon.png \
		images/FWD_icon.png
	/usr/bin/rcc -name BTres images/BTres.qrc -o /opt/raspberrytomb/.rcc/qrc_BTres.cpp

compiler_image_collection_make_all: /opt/raspberrytomb/.ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) /opt/raspberrytomb/.ui/qmake_image_collection.cpp
compiler_moc_source_make_all: /opt/raspberrytomb/.moc/qmpwidget.moc
compiler_moc_source_clean:
	-$(DEL_FILE) /opt/raspberrytomb/.moc/qmpwidget.moc
/opt/raspberrytomb/.moc/qmpwidget.moc: src/qmpwidget.h \
		src/qmpyuvreader.h \
		src/qmpwidget.cpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qmpwidget.cpp -o /opt/raspberrytomb/.moc/qmpwidget.moc

compiler_uic_make_all: /opt/raspberrytomb/.ui/ui_prefdialog.h /opt/raspberrytomb/.ui/ui_about.h /opt/raspberrytomb/.ui/ui_newplaylist.h /opt/raspberrytomb/.ui/ui_beaglemain.h /opt/raspberrytomb/.ui/ui_openplaylist.h
compiler_uic_clean:
	-$(DEL_FILE) /opt/raspberrytomb/.ui/ui_prefdialog.h /opt/raspberrytomb/.ui/ui_about.h /opt/raspberrytomb/.ui/ui_newplaylist.h /opt/raspberrytomb/.ui/ui_beaglemain.h /opt/raspberrytomb/.ui/ui_openplaylist.h
/opt/raspberrytomb/.ui/ui_prefdialog.h: src/prefdialog.ui
	/usr/bin/uic-qt4 src/prefdialog.ui -o /opt/raspberrytomb/.ui/ui_prefdialog.h

/opt/raspberrytomb/.ui/ui_about.h: src/about.ui
	/usr/bin/uic-qt4 src/about.ui -o /opt/raspberrytomb/.ui/ui_about.h

/opt/raspberrytomb/.ui/ui_newplaylist.h: src/newplaylist.ui
	/usr/bin/uic-qt4 src/newplaylist.ui -o /opt/raspberrytomb/.ui/ui_newplaylist.h

/opt/raspberrytomb/.ui/ui_beaglemain.h: src/beaglemain.ui
	/usr/bin/uic-qt4 src/beaglemain.ui -o /opt/raspberrytomb/.ui/ui_beaglemain.h

/opt/raspberrytomb/.ui/ui_openplaylist.h: src/openplaylist.ui
	/usr/bin/uic-qt4 src/openplaylist.ui -o /opt/raspberrytomb/.ui/ui_openplaylist.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_moc_source_clean compiler_uic_clean 

####### Compile

/opt/raspberrytomb/.obj/main.o: src/main.cpp src/beaglemain.h \
		src/sync.h \
		src/mysqlconn.h \
		src/songObj.h \
		src/readDB.h \
		src/radioObj.h \
		src/preferences.h \
		src/mplaycon.h \
		src/qmpwidget.h \
		src/playlistobj.h \
		src/prefdialog.h \
		src/about.h \
		src/newplaylist.h \
		src/openplaylist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/main.o src/main.cpp

/opt/raspberrytomb/.obj/beaglemain.o: src/beaglemain.cpp src/beaglemain.h \
		src/sync.h \
		src/mysqlconn.h \
		src/songObj.h \
		src/readDB.h \
		src/radioObj.h \
		src/preferences.h \
		src/mplaycon.h \
		src/qmpwidget.h \
		src/playlistobj.h \
		src/prefdialog.h \
		src/about.h \
		src/newplaylist.h \
		src/openplaylist.h \
		/opt/raspberrytomb/.ui/ui_beaglemain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/beaglemain.o src/beaglemain.cpp

/opt/raspberrytomb/.obj/sync.o: src/sync.cpp src/sync.h \
		src/mysqlconn.h \
		src/songObj.h \
		src/readDB.h \
		src/radioObj.h \
		src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/sync.o src/sync.cpp

/opt/raspberrytomb/.obj/songObj.o: src/songObj.cpp src/songObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/songObj.o src/songObj.cpp

/opt/raspberrytomb/.obj/readDB.o: src/readDB.cpp src/readDB.h \
		src/songObj.h \
		src/radioObj.h \
		src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/readDB.o src/readDB.cpp

/opt/raspberrytomb/.obj/qmpwidget.o: src/qmpwidget.cpp src/qmpwidget.h \
		src/qmpyuvreader.h \
		/opt/raspberrytomb/.moc/qmpwidget.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/qmpwidget.o src/qmpwidget.cpp

/opt/raspberrytomb/.obj/preferences.o: src/preferences.cpp src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/preferences.o src/preferences.cpp

/opt/raspberrytomb/.obj/prefdialog.o: src/prefdialog.cpp src/prefdialog.h \
		src/preferences.h \
		/opt/raspberrytomb/.ui/ui_prefdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/prefdialog.o src/prefdialog.cpp

/opt/raspberrytomb/.obj/mysqlconn.o: src/mysqlconn.cpp src/mysqlconn.h \
		src/songObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/mysqlconn.o src/mysqlconn.cpp

/opt/raspberrytomb/.obj/mplaycon.o: src/mplaycon.cpp src/mplaycon.h \
		src/qmpwidget.h \
		src/preferences.h \
		src/playlistobj.h \
		src/songObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/mplaycon.o src/mplaycon.cpp

/opt/raspberrytomb/.obj/about.o: src/about.cpp src/about.h \
		/opt/raspberrytomb/.ui/ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/about.o src/about.cpp

/opt/raspberrytomb/.obj/newplaylist.o: src/newplaylist.cpp src/newplaylist.h \
		src/preferences.h \
		src/ui_newplaylist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/newplaylist.o src/newplaylist.cpp

/opt/raspberrytomb/.obj/playlistobj.o: src/playlistobj.cpp src/playlistobj.h \
		src/songObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/playlistobj.o src/playlistobj.cpp

/opt/raspberrytomb/.obj/openplaylist.o: src/openplaylist.cpp src/openplaylist.h \
		src/preferences.h \
		/opt/raspberrytomb/.ui/ui_openplaylist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/openplaylist.o src/openplaylist.cpp

/opt/raspberrytomb/.obj/radioObj.o: src/radioObj.cpp src/radioObj.h \
		src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/radioObj.o src/radioObj.cpp

/opt/raspberrytomb/.obj/moc_beaglemain.o: /opt/raspberrytomb/.moc/moc_beaglemain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/moc_beaglemain.o /opt/raspberrytomb/.moc/moc_beaglemain.cpp

/opt/raspberrytomb/.obj/moc_qmpyuvreader.o: /opt/raspberrytomb/.moc/moc_qmpyuvreader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/moc_qmpyuvreader.o /opt/raspberrytomb/.moc/moc_qmpyuvreader.cpp

/opt/raspberrytomb/.obj/moc_qmpwidget.o: /opt/raspberrytomb/.moc/moc_qmpwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/moc_qmpwidget.o /opt/raspberrytomb/.moc/moc_qmpwidget.cpp

/opt/raspberrytomb/.obj/moc_prefdialog.o: /opt/raspberrytomb/.moc/moc_prefdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/moc_prefdialog.o /opt/raspberrytomb/.moc/moc_prefdialog.cpp

/opt/raspberrytomb/.obj/moc_about.o: /opt/raspberrytomb/.moc/moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/moc_about.o /opt/raspberrytomb/.moc/moc_about.cpp

/opt/raspberrytomb/.obj/moc_newplaylist.o: /opt/raspberrytomb/.moc/moc_newplaylist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/moc_newplaylist.o /opt/raspberrytomb/.moc/moc_newplaylist.cpp

/opt/raspberrytomb/.obj/moc_openplaylist.o: /opt/raspberrytomb/.moc/moc_openplaylist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/moc_openplaylist.o /opt/raspberrytomb/.moc/moc_openplaylist.cpp

/opt/raspberrytomb/.obj/qrc_BTres.o: /opt/raspberrytomb/.rcc/qrc_BTres.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /opt/raspberrytomb/.obj/qrc_BTres.o /opt/raspberrytomb/.rcc/qrc_BTres.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/raspberrytomb/ || $(MKDIR) $(INSTALL_ROOT)/opt/raspberrytomb/ 
	-$(INSTALL_PROGRAM) "/opt/raspberrytomb/$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/raspberrytomb/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/opt/raspberrytomb/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/raspberrytomb/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/raspberrytomb/ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/raspberrytomb/src/ || $(MKDIR) $(INSTALL_ROOT)/opt/raspberrytomb/src/ 
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/about.cpp $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/about.h $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/about.ui $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/beaglemain.cpp $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/beaglemain.h $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/beaglemain.ui $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/main.cpp $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/mplaycon.cpp $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/mplaycon.h $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/mysqlconn.cpp $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/mysqlconn.h $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/newplaylist.cpp $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/newplaylist.h $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/newplaylist.ui $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/openplaylist.cpp $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/openplaylist.h $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/openplaylist.ui $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/playlistobj.cpp $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/playlistobj.h $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/prefdialog.cpp $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/prefdialog.h $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/prefdialog.ui $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/preferences.cpp $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/preferences.h $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/qmpwidget.cpp $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/qmpwidget.h $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/qmpwidget.pri $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/qmpyuvreader.h $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/radioObj.cpp $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/radioObj.h $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/readDB.cpp $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/readDB.h $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/songObj.cpp $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/songObj.h $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/src.pro $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/sync.cpp $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/sync.h $(INSTALL_ROOT)/opt/raspberrytomb/src/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src/ui_newplaylist.h $(INSTALL_ROOT)/opt/raspberrytomb/src/


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/about.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/about.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/about.ui 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/beaglemain.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/beaglemain.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/beaglemain.ui 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/main.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/mplaycon.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/mplaycon.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/mysqlconn.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/mysqlconn.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/newplaylist.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/newplaylist.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/newplaylist.ui 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/openplaylist.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/openplaylist.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/openplaylist.ui 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/playlistobj.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/playlistobj.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/prefdialog.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/prefdialog.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/prefdialog.ui 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/preferences.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/preferences.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/qmpwidget.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/qmpwidget.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/qmpwidget.pri 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/qmpyuvreader.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/radioObj.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/radioObj.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/readDB.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/readDB.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/songObj.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/songObj.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/src.pro 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/sync.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/sync.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src/ui_newplaylist.h
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/raspberrytomb/src/ 


install_documentation: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/ 
	-$(INSTALL_PROGRAM) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/docs/compile.sh $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/
	-strip $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/compile.sh
	-$(INSTALL_PROGRAM) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/docs/configure.sh $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/
	-strip $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/configure.sh
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/docs/HostSetupREAD $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/
	-$(INSTALL_PROGRAM) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/docs/install.sh $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/
	-strip $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/install.sh
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/docs/instprint.sh $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/docs/instructions $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/docs/README.txt $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/docs/readme_install.txt $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/


uninstall_documentation:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/compile.sh 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/configure.sh 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/HostSetupREAD 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/install.sh 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/instprint.sh 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/instructions 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/README.txt 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/readme_install.txt
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/raspberrytomb/doc/ 


install_other: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/raspberrytomb/ || $(MKDIR) $(INSTALL_ROOT)/opt/raspberrytomb/ 
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/changelog $(INSTALL_ROOT)/opt/raspberrytomb/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/copyright $(INSTALL_ROOT)/opt/raspberrytomb/
	-$(INSTALL_DIR) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/docs $(INSTALL_ROOT)/opt/raspberrytomb/
	-$(INSTALL_DIR) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/images $(INSTALL_ROOT)/opt/raspberrytomb/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/Makefile $(INSTALL_ROOT)/opt/raspberrytomb/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/raspberrytomb.pro $(INSTALL_ROOT)/opt/raspberrytomb/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/raspberrytomb.pro.user $(INSTALL_ROOT)/opt/raspberrytomb/
	-$(INSTALL_FILE) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/readme.txt $(INSTALL_ROOT)/opt/raspberrytomb/
	-$(INSTALL_DIR) /home/skynet/beagletomb/raspberry_release/github/raspberrytomb/src $(INSTALL_ROOT)/opt/raspberrytomb/


uninstall_other:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/changelog 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/copyright 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/docs 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/images 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/Makefile 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/raspberrytomb.pro 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/raspberrytomb.pro.user 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/readme.txt 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/raspberrytomb/src
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/raspberrytomb/ 


install:  install_target install_sources install_documentation install_other  FORCE

uninstall: uninstall_target uninstall_sources uninstall_documentation uninstall_other   FORCE

FORCE:

